---
title: "Resume"

---

# **Lilly Zapalac**

Fort Collins, CO, 80524 \| (361)-557-1098 \| [**Lillyannezap\@gmail.com**](mailto:Lillyannezap@gmail.com) \| [**linkedin.com/in/lillyzapalac**](http://linkedin.com/in/lillyzapalac)

I am an emerging ecologist who is interested in marine ecosystems and community building. I long to make information on environmental issues that directly impact both human and marine species way of life by making information more accessible to the public. Therefore, I aim to take the communication skills that I have now and add on to better reach the desired audiences.

# 

# **Education**

# Colorado State University, Fort Collins, CO — Ecosystem Science and Sustainability 	Aug.2022 - Dec.2025  Minor: Environmental Studies in the Liberal Arts	GPA: 3.96

\

# **Professional Experience**

## Colorado State University, Fort Collins, CO — Calculus Tutor	Jan.2023-Present

-   Perform diverse learning techniques to cater to different learning styles

-   Create an environment for students to feel comfortable with asking for help

-   Communicate with more experienced tutors to better teach students

\

## **Academic Experience** 

## Colorado State University, Fort Collins, CO— Supervised College Teaching 	Aug. 2023- Dec.2023

-   Used practice sessions to implement better teaching strategies

-   Implemented strategies learned in a tutoring atmosphere

\

# **Awards and Honors**

Colorado State University Dean’s List 	Fall 2022-Present

National Residence Hall Honorary Award 	Spring 2024

\

# **Skills**

-   Effective communication with different stakeholders

-   Diplomatic

-   Always takes initiative

-   Action-oriented
